### ISSUE TITLE
Test "thread pool executor 2" reports an error

### ISSUE THREAD

**Issue by svenha** [donaldsonjw/bigloo-concurrent#1]
Here are the details from `make test`:

    thread pool executor 2... ok.
    *** ERROR:executor:
    Failed to add task -- #f
        1. abort-rejected-handler@bigloo-concurrent/executor, src/Llib/executor.scm:173
        2. <@default-rejected-h1251:/var/tmp/bigloo-concurrent/src/Llib/executor,scm:215@>:%toplevel@bigloo-concurrent/executor, src/Llib/executor.scm:215
        3. execute-future!-<thr1244, src/Llib/executor.scm:266
        4. execute-future!@bigloo-concurrent/executor, src/Llib/executor.scm:137
        5. &thread1126
    concurrent executor... ok.

Could this test hit some `ulimit`?

**Comment by donaldsonjw** [comment]
Sven,
I understand the confusion but the error message above is the behavior being tested for. The test is looking for an exception to be raised when all threads of the threadpool are occupied. I will work on removing the message from the testing output to prevent future confusion.

**Comment by svenha** [comment]
Thanks. This explains why the test statistics shows only successes.
